import { act } from '@stories/mock-backend';

const data = {
  amount: 5,
  energy: 368900,
  maxEnergy: 400000,
  displayedUnits: 3689,
  displayedMaxUnits: 4000,
  showpH: 1,
  chemicals: [
    {
      title: 'Aluminium',
      id: 'Aluminium',
      pH: 7,
      color: '#A8A8A8',
      pHCol: 'green',
    },
    {
      title: 'Bromine',
      id: 'Bromine',
      pH: 7.8,
      color: '#D35415',
      pHCol: 'green',
    },
    {
      title: 'Carbon',
      id: 'Carbon',
      pH: 5,
      color: '#1C1300',
      pHCol: 'olive',
    },
    {
      title: 'Chlorine',
      id: 'Chlorine',
      pH: 7.4,
      color: '#FFFB89',
      pHCol: 'green',
    },
    {
      title: 'Copper',
      id: 'Copper',
      pH: 5.5,
      color: '#6E3B08',
      pHCol: 'good',
    },
    {
      title: 'Ethanol',
      id: 'Ethanol',
      pH: 7.33,
      color: '#404030',
      pHCol: 'green',
    },
    {
      title: 'Fluorine',
      id: 'Fluorine',
      pH: 2,
      color: '#808080',
      pHCol: 'orange',
    },
    {
      title: 'Hydrogen',
      id: 'Hydrogen',
      pH: 0.1,
      color: '#808080',
      pHCol: 'red',
    },
    {
      title: 'Iodine',
      id: 'Iodine',
      pH: 4.5,
      color: '#BC8A00',
      pHCol: 'olive',
    },
    {
      title: 'Iron',
      id: 'Iron',
      pH: 6,
      color: '#606060',
      pHCol: 'good',
    },
    {
      title: 'Lithium',
      id: 'Lithium',
      pH: 11.3,
      color: '#808080',
      pHCol: 'violet',
    },
    {
      title: 'Mercury',
      id: 'Mercury',
      pH: 7,
      color: '#484848',
      pHCol: 'green',
    },
    {
      title: 'Nitrogen',
      id: 'Nitrogen',
      pH: 7,
      color: '#808080',
      pHCol: 'green',
    },
    {
      title: 'Oxygen',
      id: 'Oxygen',
      pH: 9.2,
      color: '#808080',
      pHCol: 'teal',
    },
    {
      title: 'Phosphorus',
      id: 'Phosphorus',
      pH: 6.5,
      color: '#832828',
      pHCol: 'green',
    },
    {
      title: 'Potassium',
      id: 'Potassium',
      pH: 7,
      color: '#A0A0A0',
      pHCol: 'green',
    },
    {
      title: 'Radium',
      id: 'Radium',
      pH: 10,
      color: '#00CC00',
      pHCol: 'blue',
    },
    {
      title: 'Silicon',
      id: 'Silicon',
      pH: 10,
      color: '#A8A8A8',
      pHCol: 'blue',
    },
    {
      title: 'Sodium',
      id: 'Sodium',
      pH: 11.6,
      color: '#808080',
      pHCol: 'violet',
    },
    {
      title: 'Stable Plasma',
      id: 'Stable Plasma',
      pH: 1.5,
      color: '#2D2D2D',
      pHCol: 'orange',
    },
    {
      title: 'Sugar',
      id: 'Sugar',
      pH: 7,
      color: '#FFFFFF',
      pHCol: 'green',
    },
    {
      title: 'Sulfur',
      id: 'Sulfur',
      pH: 4.5,
      color: '#BF8C00',
      pHCol: 'olive',
    },
    {
      title: 'Sulfuric Acid',
      id: 'Sulfuric Acid',
      pH: 2.75,
      color: '#00FF32',
      pHCol: 'average',
    },
    {
      title: 'Water',
      id: 'Water',
      pH: 7,
      color: '#AAAAAA77',
      pHCol: 'green',
    },
    {
      title: 'Welding Fuel',
      id: 'Welding Fuel',
      pH: 4,
      color: '#660000',
      pHCol: 'yellow',
    },
    {
      title: 'Acetone',
      id: 'Acetone',
      pH: 7,
      color: '#AF14B7',
      pHCol: 'green',
    },
    {
      title: 'Ammonia',
      id: 'Ammonia',
      pH: 11.6,
      color: '#404030',
      pHCol: 'violet',
    },
    {
      title: 'Ash',
      id: 'Ash',
      pH: 6.5,
      color: '#515151',
      pHCol: 'green',
    },
    {
      title: 'Diethylamine',
      id: 'Diethylamine',
      pH: 12,
      color: '#604030',
      pHCol: 'violet',
    },
    {
      title: 'Oil',
      id: 'Oil',
      pH: 4,
      color: '#2D2D2D',
      pHCol: 'yellow',
    },
    {
      title: 'Saltpetre',
      id: 'Saltpetre',
      pH: 11.2,
      color: '#60A584',
      pHCol: 'violet',
    },
    {
      title: 'Carpotoxin',
      id: 'Carpotoxin',
      pH: 12,
      color: '#003333',
      pHCol: 'violet',
    },
    {
      title: "Miner's Salve",
      id: "Miner's Salve",
      pH: 2.6,
      color: '#6D6374',
      pHCol: 'average',
    },
    {
      title: 'Morphine',
      id: 'Morphine',
      pH: 8.96,
      color: '#A9FBFB',
      pHCol: 'teal',
    },
    {
      title: 'Space Drugs',
      id: 'Space Drugs',
      pH: 9,
      color: '#60A584',
      pHCol: 'teal',
    },
    {
      title: 'Toxin',
      id: 'Toxin',
      pH: 7,
      color: '#CF3600',
      pHCol: 'green',
    },
  ],
  recipes: [],
  recordingRecipe: null,
  recipeReagents: [],
  beaker: {
    maxVolume: 100,
    transferAmounts: [5, 10, 15, 20, 25, 30, 50, 100],
    pH: 10,
    currentVolume: 35,
    contents: [
      { name: 'Space Drugs', volume: 20 },
      { name: 'Carpotoxin', volume: 10 },
      { name: 'Radium', volume: 5 },
    ],
  },
};

export function useBackend<TData>() {
  return {
    act,
    data: data as TData,
  };
}
