declare const classNames: {
  readonly noticeBox: "noticeBox";
  readonly color__black: "color__black";
  readonly color__white: "color__white";
  readonly color__red: "color__red";
  readonly color__orange: "color__orange";
  readonly color__yellow: "color__yellow";
  readonly color__olive: "color__olive";
  readonly color__green: "color__green";
  readonly color__teal: "color__teal";
  readonly color__blue: "color__blue";
  readonly color__violet: "color__violet";
  readonly color__purple: "color__purple";
  readonly color__pink: "color__pink";
  readonly color__brown: "color__brown";
  readonly color__grey: "color__grey";
  readonly "color__light-grey": "color__light-grey";
  readonly color__good: "color__good";
  readonly color__average: "color__average";
  readonly color__bad: "color__bad";
  readonly color__label: "color__label";
  readonly info: "info";
  readonly success: "success";
  readonly warning: "warning";
  readonly danger: "danger";
};
export = classNames;
