export const airAlarmData = {
  locked: 0,
  siliconUser: 0,
  emagged: 0,
  dangerLevel: 0,
  atmosAlarm: 0,
  fireAlarm: 0,
  faultStatus: 0,
  faultLocation: null,
  sensor: 0,
  allowLinkChange: 1,
  envData: [
    { name: 'Pressure', value: '101.34 kPa', danger: 0 },
    {
      name: 'Temperature',
      value: '293.15 Kelvin / 20 Celcius',
      danger: 0,
    },
    {
      name: 'Oxygen',
      value: '22 moles / 21.15 % / 21.44 kPa',
      danger: 0,
    },
    {
      name: 'Nitrogen',
      value: '82 moles / 78.85 % / 79.9 kPa',
      danger: 0,
    },
  ],
  tlvSettings: [
    {
      name: 'Pressure',
      unit: 'kPa',
      id: 'pressure',
      warning_min: 50,
      hazard_min: 20,
      warning_max: 325,
      hazard_max: 550,
    },
    {
      name: 'Temperature',
      unit: 'K',
      id: 'temperature',
      warning_min: 280.15,
      hazard_min: 270.15,
      warning_max: 313.15,
      hazard_max: 340.15,
    },
    {
      name: 'Oxygen',
      unit: 'kPa',
      id: '/datum/gas/oxygen',
      warning_min: 19,
      hazard_min: 16,
      warning_max: -1,
      hazard_max: -1,
    },
    {
      name: 'Nitrogen',
      unit: 'kPa',
      id: '/datum/gas/nitrogen',
      warning_min: -1,
      hazard_min: -1,
      warning_max: -1,
      hazard_max: -1,
    },
    {
      name: 'Carbon Dioxide',
      unit: 'kPa',
      id: '/datum/gas/carbon_dioxide',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 5,
      hazard_max: 10,
    },
    {
      name: 'Plasma',
      unit: 'kPa',
      id: '/datum/gas/plasma',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Water Vapor',
      unit: 'kPa',
      id: '/datum/gas/water_vapor',
      warning_min: -1,
      hazard_min: -1,
      warning_max: -1,
      hazard_max: -1,
    },
    {
      name: 'Hyper-noblium',
      unit: 'kPa',
      id: '/datum/gas/hypernoblium',
      warning_min: -1,
      hazard_min: -1,
      warning_max: -1,
      hazard_max: -1,
    },
    {
      name: 'Nitrous Oxide',
      unit: 'kPa',
      id: '/datum/gas/nitrous_oxide',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Nitrium',
      unit: 'kPa',
      id: '/datum/gas/nitrium',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Tritium',
      unit: 'kPa',
      id: '/datum/gas/tritium',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'BZ',
      unit: 'kPa',
      id: '/datum/gas/bz',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Pluoxium',
      unit: 'kPa',
      id: '/datum/gas/pluoxium',
      warning_min: -1,
      hazard_min: -1,
      warning_max: -1,
      hazard_max: -1,
    },
    {
      name: 'Miasma',
      unit: 'kPa',
      id: '/datum/gas/miasma',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Freon',
      unit: 'kPa',
      id: '/datum/gas/freon',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Hydrogen',
      unit: 'kPa',
      id: '/datum/gas/hydrogen',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Healium',
      unit: 'kPa',
      id: '/datum/gas/healium',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Proto Nitrate',
      unit: 'kPa',
      id: '/datum/gas/proto_nitrate',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Zauker',
      unit: 'kPa',
      id: '/datum/gas/zauker',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Halon',
      unit: 'kPa',
      id: '/datum/gas/halon',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
    {
      name: 'Helium',
      unit: 'kPa',
      id: '/datum/gas/helium',
      warning_min: -1,
      hazard_min: -1,
      warning_max: -1,
      hazard_max: -1,
    },
    {
      name: 'Antinoblium',
      unit: 'kPa',
      id: '/datum/gas/antinoblium',
      warning_min: -1,
      hazard_min: -1,
      warning_max: 0.2,
      hazard_max: 0.5,
    },
  ],
  vents: [
    {
      refID: '[0x2002a17]',
      long_name: 'Primary Tool Storage omni air vent qDgLI',
      power: 1,
      overclock: 0,
      integrity: 1,
      checks: 1,
      excheck: 1,
      incheck: 0,
      direction: 1,
      external: 101.325,
      internal: 0,
      extdefault: 1,
      intdefault: 1,
    },
  ],
  scrubbers: [],
  selectedModePath: '/datum/air_alarm_mode/filtering',
  modes: [
    {
      name: 'Filtering',
      desc: 'Scrubs out contaminants',
      danger: 0,
      path: '/datum/air_alarm_mode/filtering',
    },
    {
      name: 'Contaminated',
      desc: 'Scrubs out ALL contaminants quickly',
      danger: 0,
      path: '/datum/air_alarm_mode/contaminated',
    },
    {
      name: 'Draught',
      desc: 'Siphons out air while replacing',
      danger: 0,
      path: '/datum/air_alarm_mode/draught',
    },
    {
      name: 'Refill',
      desc: 'Triple vent output',
      danger: 1,
      path: '/datum/air_alarm_mode/refill',
    },
    {
      name: 'Cycle',
      desc: 'Siphons air before replacing',
      danger: 1,
      path: '/datum/air_alarm_mode/cycle',
    },
    {
      name: 'Siphon',
      desc: 'Siphons air out of the room',
      danger: 1,
      path: '/datum/air_alarm_mode/siphon',
    },
    {
      name: 'Panic Siphon',
      desc: 'Siphons air out of the room quickly',
      danger: 1,
      path: '/datum/air_alarm_mode/panic_siphon',
    },
    {
      name: 'Off',
      desc: 'Shuts off vents and scrubbers',
      danger: 0,
      path: '/datum/air_alarm_mode/off',
    },
  ],
  panicSiphonPath: '/datum/air_alarm_mode/panic_siphon',
  filteringPath: '/datum/air_alarm_mode/filtering',
  thresholdTypeMap: {
    warning_min: 1,
    hazard_min: 2,
    warning_max: 4,
    hazard_max: 8,
    all: 15,
  },
} as const;
