import { act } from '@stories/mock-backend';

const data = {
  connected: 1,
  generated_domain: 'beach_bar',
  occupants: 1,
  points: 100,
  randomized: 0,
  ready: 1,
  scanner_tier: 4,
  retries_left: 2,
  broadcasting: 0,
  broadcasting_on_cd: 0,
  available_domains: [
    {
      announce_ghosts: 0,
      cost: 2,
      desc: 'Board an abductor ship and take their goodies.',
      difficulty: 2,
      id: 'abductor_ship',
      is_modular: 1,
      has_secondary_objectives: 0,
      name: 'Abductor Ship',
      reward: 4,
    },
    {
      announce_ghosts: 0,
      cost: 2,
      desc: 'Home of the ash drake, a powerful dragon that scours the surface of Lavaland.',
      difficulty: 2,
      id: 'ash_drake',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Ashen Inferno',
      reward: 4,
    },
    {
      announce_ghosts: 0,
      cost: 0,
      desc: "A cheerful seaside haven where friendly skeletons serve up drinks. Say, how'd you guys get so dead?",
      difficulty: 0,
      id: 'beach_bar',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Beach Bar',
      reward: 1,
    },
    {
      announce_ghosts: 0,
      cost: 2,
      desc: 'Few escape the surface of Lavaland without a few scars. Some remain, maddened by the hunt.',
      difficulty: 2,
      id: 'blood_drunk_miner',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Sanguine Excavation',
      reward: 4,
    },
    {
      announce_ghosts: 0,
      cost: 0,
      desc: 'A beach front town with a large forest to the north.',
      difficulty: 0,
      id: 'breeze_bay',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Breeze Bay',
      reward: 3,
    },
    {
      announce_ghosts: 0,
      cost: 3,
      desc: 'King of the slaughter demons. Bubblegum is a massive, hulking beast with a penchant for violence.',
      difficulty: 3,
      id: 'bubblegum',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Blood-Soaked Lair',
      reward: 5,
    },
    {
      announce_ghosts: 0,
      cost: 1,
      desc: 'In the deep, dark reaches of space, there is only Honk.',
      difficulty: 1,
      id: 'clown_planet',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Clown Planet',
      reward: 3,
    },
    {
      announce_ghosts: 0,
      cost: 3,
      desc: 'A massive, ancient beast named the Colossus. Judgment comes.',
      difficulty: 3,
      id: 'colossus',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Celestial Trial',
      reward: 5,
    },
    {
      announce_ghosts: 0,
      cost: 2,
      desc: 'A famous pizzeria that got ruined by what it had to offer.',
      difficulty: 2,
      id: 'fredingtonfastingbear',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Pizza Party',
      reward: 4,
    },
    {
      announce_ghosts: 0,
      cost: 0,
      desc: 'An asteroid home to a bountiful forest of gondolas. Peaceful.',
      difficulty: 0,
      id: 'gondola_asteroid',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Gondola Asteroid',
      reward: 1,
    },
    {
      announce_ghosts: 0,
      cost: 0,
      desc: 'A peaceful hunt in the wilderness.',
      difficulty: 0,
      id: 'grasslands_hunt',
      is_modular: 1,
      has_secondary_objectives: 0,
      name: 'Grasslands Hunt',
      reward: 1,
    },
    {
      announce_ghosts: 0,
      cost: 3,
      desc: 'Dance, puppets, dance!',
      difficulty: 3,
      id: 'hierophant',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Zealot Arena',
      reward: 5,
    },
    {
      announce_ghosts: 1,
      cost: 3,
      desc: "A 'peaceful' island tucked away in the middle of nowhere. This map will auto-complete after a number of deaths have occurred.",
      difficulty: 3,
      id: 'island_brawl',
      is_modular: 0,
      has_secondary_objectives: 1,
      name: 'Island Brawl',
      reward: 5,
    },
    {
      announce_ghosts: 1,
      cost: 1,
      desc: 'Every so often, workers demand rights from Nanotrasen. This is unprofitable.',
      difficulty: 1,
      id: 'meta_central',
      is_modular: 1,
      has_secondary_objectives: 0,
      name: 'Meta Central',
      reward: 3,
    },
    {
      announce_ghosts: 0,
      cost: 1,
      desc: 'An abandoned and infested factory manufacturing disposal pipes.',
      difficulty: 1,
      id: 'pipedream',
      is_modular: 1,
      has_secondary_objectives: 0,
      name: 'Disposal Pipe Factory',
      reward: 3,
    },
    {
      announce_ghosts: 1,
      cost: 2,
      desc: 'Battle your way to the hidden treasure, seize the booty, and make a swift escape before the pirates turn the tide.',
      difficulty: 2,
      id: 'pirates',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Corsair Cove',
      reward: 4,
    },
    {
      announce_ghosts: 0,
      cost: 1,
      desc: 'Sneak into an abandoned corner of the virtual world, where they store all of the crates. Warning -- Virtual domain does not support visual display. This mission must be completed using echolocation.',
      difficulty: 2,
      id: 'psyker_shuffle',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Crate Chaos',
      reward: 5,
    },
    {
      announce_ghosts: 0,
      cost: 2,
      desc: 'Another neglected corner of the virtual world. This one had to be abandoned due to zombie virus. Warning -- Virtual domain does not support visual display. This mission must be completed using echolocation.',
      difficulty: 2,
      id: 'psyker_zombies',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Infected Domain',
      reward: 5,
    },
    {
      announce_ghosts: 0,
      cost: 1,
      desc: 'A treacherous climb few calves can survive. Great cardio though.',
      difficulty: 1,
      id: 'stairs_and_cliffs',
      is_modular: 0,
      has_secondary_objectives: 1,
      name: 'Glacier Grind',
      reward: 4,
    },
    {
      announce_ghosts: 1,
      cost: 2,
      desc: 'Board the enemy ship and recover the stolen cargo.',
      difficulty: 2,
      id: 'syndicate_assault',
      is_modular: 1,
      has_secondary_objectives: 0,
      name: 'Syndicate Assault',
      reward: 4,
    },
    {
      announce_ghosts: 0,
      cost: 20,
      desc: 'Suspended in the silent void of space, the Neon Relic is a haunting echo of a retro-futuristic era. Hang out, enjoy the view.',
      difficulty: 0,
      id: 'vaporwave',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Cosmic Vestige',
      reward: 6,
    },
    {
      announce_ghosts: 0,
      cost: 3,
      desc: 'Legends speak of the ravenous Wendigo hidden deep within the caves of Icemoon.',
      difficulty: 3,
      id: 'wendigo',
      is_modular: 0,
      has_secondary_objectives: 0,
      name: 'Glacial Devourer',
      reward: 5,
    },
    {
      announce_ghosts: 0,
      cost: 1,
      desc: 'Our ship scanners have detected lifeforms of unknown origin. Friendly attempts to contact them have failed.',
      difficulty: 1,
      id: 'xeno_nest',
      is_modular: 1,
      has_secondary_objectives: 0,
      name: 'Xeno Infestation',
      reward: 3,
    },
  ],
  avatars: [
    {
      health: 100,
      name: 'SakuraSn1per',
      pilot: 'Dawson Blyant',
      brute: 0,
      burn: 0,
      tox: 0,
      oxy: 0,
    },
  ],
};

export function useBackend<TData>() {
  return {
    act,
    data: data as TData,
  };
}
