import { useFuzzySearch } from '../lib/components/FuzzySearch';
import type { Meta, StoryObj } from '@storybook/react';
import { Box } from '../lib/components/Box';
import { Input } from '../lib/components/Input';

const items = [
  "Cherries - Bing, Canned",
  "Yogurt - Strawberry, 175 Gr",
  "Skirt - 29 Foot",
  "Dawn Professionl Pot And Pan",
  "Wine - Casablanca Valley",
  "Piping - Bags Quizna",
  "Wine - Wyndham Estate Bin 777",
  "Bread Foccacia Whole",
  "Sugar - Brown",
  "Coffee - Espresso",
  "Salmon Steak - Cohoe 8 Oz",
  "Jam - Raspberry,jar",
  "Loaf Pan - 2 Lb, Foil",
  "Dikon",
  "Bread - Roll, Soft White Round",
  "Ocean Spray - Ruby Red",
  "Extract - Raspberry",
  "Cookie Dough - Oatmeal Rasin",
  "Turkey - Ground. Lean",
  "Bread - Granary Small Pull",
  "Beef - Ground Lean Fresh",
  "Compound - Raspberry",
  "Tomatoes - Roma",
  "Puff Pastry - Sheets",
  "Veal - Tenderloin, Untrimmed",
  "Pastry - Lemon Danish - Mini",
  "Mushroom - Porcini Frozen",
  "Goat - Whole Cut",
  "Beer - Sleemans Honey Brown",
  "Soup - Verve - Chipotle Chicken",
  "Cookies Oatmeal Raisin",
  "Muffin Batt - Choc Chk",
  "Wine - Baron De Rothschild",
  "Cheese - Woolwich Goat, Log",
  "Ketchup - Tomato",
  "Foam Cup 6 Oz",
  "Juice - Ocean Spray Kiwi",
  "Sobe - Tropical Energy",
  "Crackers - Soda / Saltins",
  "Bread Fig And Almond",
  "Sauce - Gravy, Au Jus, Mix",
  "Sage - Ground",
  "Bread - Multigrain, Loaf",
  "Soup - Campbells - Tomato",
  "Munchies Honey Sweet Trail Mix",
  "Grapes - Green",
  "Chicken - Breast, 5 - 7 Oz",
  "Squid - U - 10 Thailand",
  "Bread - Raisin",
  "Wine - Maipo Valle Cabernet",
  "Chicken Giblets",
  "Pur Value",
  "Trout - Rainbow, Frozen",
  "Pie Filling - Apple",
  "Halibut - Steaks",
  "Puree - Mocha",
  "Pepper - Orange",
  "Scallops - Live In Shell",
  "Wine - Red, Colio Cabernet",
  "Rice Paper",
  "Butter - Salted, Micro",
  "Wine - Cahors Ac 2000, Clos",
  "Cocoa Butter",
  "Eggplant Oriental",
  "Plate Foam Laminated 9in Blk",
  "Yokaline",
  "Cookie Dough - Chunky",
  "Salmon - Fillets",
  "Egg Patty Fried",
  "Milk Powder",
  "Icecream - Dibs",
  "Vinegar - Sherry",
  "Crackers - Graham",
  "Wine - Magnotta - Pinot Gris Sr",
  "Veal - Kidney",
  "Cheese - Pied De Vents",
  "Sauce - Sesame Thai Dressing",
  "Cod - Fillets",
  "Pimento - Canned",
  "Potatoes - Mini White 3 Oz",
  "Macaroons - Homestyle Two Bit",
  "Tuna - Loin",
  "Bowl 12 Oz - Showcase 92012",
  "Chambord Royal",
  "Lettuce - Green Leaf",
  "Mousse - Banana Chocolate",
  "Sauce - Caesar Dressing",
  "Cake - Sheet Strawberry",
  "Beef - Short Loin",
  "Lumpfish Black",
  "Potatoes - Idaho 80 Count",
  "Wine - Muscadet Sur Lie",
  "Yogurt - Banana, 175 Gr",
  "Sausage - Meat",
  "Mortadella",
  "Chocolate - Pistoles, Lactee, Milk",
  "Pizza Pizza Dough",
  "Sugar - White Packet",
  "Lemon Balm - Fresh",
  "Vermacelli - Sprinkles, Assorted",
  "Macaroons - Two Bite Choc",
  "Wine - Hardys Bankside Shiraz",
  "Tilapia - Fillets",
  "Sprite, Diet - 355ml",
  "Blue Curacao - Marie Brizard",
  "Lemonade - Island Tea, 591 Ml",
  "Port - 74 Brights",
  "Sauce - Chili",
  "Ginger - Fresh",
  "Wine - Winzer Krems Gruner",
  "Bag - Bread, White, Plain",
  "Vermouth - Sweet, Cinzano",
  "Cod - Fillets",
  "Chef Hat 25cm",
  "Mop Head - Cotton, 24 Oz",
  "Vermouth - White, Cinzano",
  "Cookie Trail Mix",
  "Bread - Pumpernickel",
  "Grand Marnier",
  "Placemat - Scallop, White",
  "Potatoes - Idaho 100 Count",
  "Pepper - Pablano",
  "Chips - Assorted",
  "Energy Drink Bawls",
  "Shrimp - Black Tiger 6 - 8",
  "Apple - Macintosh",
  "Fish - Artic Char, Cold Smoked",
  "Soup - Campbells, Lentil",
  "Flour - Strong",
  "Muffin Mix - Banana Nut",
  "Kiwano",
  "Flavouring - Raspberry",
  "Dikon",
  "Bay Leaf Fresh",
  "Wood Chips - Regular",
  "Soup - Campbells, Beef Barley",
  "Energy Drink",
  "Compound - Pear",
  "Vermacelli - Sprinkles, Assorted",
  "Chicken - Leg / Back Attach",
  "Pork - Bacon, Sliced",
  "Cornstarch",
  "Juice - Tomato, 10 Oz",
  "Arizona - Plum Green Tea",
  "Sansho Powder",
  "Assorted Desserts",
  "Cake - Dulce De Leche",
  "Wine - Fume Blanc Fetzer",
  "Sauce - Cranberry",
  "Cookie Dough - Double",
  "Glaze - Clear",
  "Food Colouring - Orange",
  "Nestea - Iced Tea",
  "Wine - Cotes Du Rhone",
  "Tahini Paste",
  "Ecolab Crystal Fusion",
  "Lamb - Leg, Bone In",
  "Napkin - Beverage 1 Ply",
  "Wine - Vovray Sec Domaine Huet",
  "Radish - Black, Winter, Organic",
  "Wine - Lamancha Do Crianza",
  "Wine - Sogrape Mateus Rose",
  "Truffle - Whole Black Peeled",
  "Coffee - Beans, Whole",
  "Soap - Hand Soap",
  "Marsala - Sperone, Fine, D.o.c.",
  "Napkin Colour",
  "Wine - Rosso Del Veronese Igt",
  "Cheese - Victor Et Berthold",
  "Soup - Campbells Bean Medley",
  "Tomato Puree",
  "Capers - Pickled",
  "Halibut - Whole, Fresh",
  "Godiva White Chocolate",
  "Tart - Lemon",
  "Versatainer Nc - 9388",
  "Mangoes",
  "Tray - 12in Rnd Blk",
  "Gatorade - Fruit Punch",
  "Bread - French Baquette",
  "Muffin Mix - Corn Harvest",
  "Container - Clear 16 Oz",
  "Veal - Ground",
  "Scampi Tail",
  "Lamb Shoulder Boneless Nz",
  "Pepper - Sorrano",
  "Sauce Bbq Smokey",
  "Carbonated Water - Wildberry",
  "Ham - Cooked",
  "Caviar - Salmon",
  "Wine - Placido Pinot Grigo",
  "Olive - Spread Tapenade",
  "Parsley - Dried",
  "Sage Ground Wiberg",
  "Lettuce - Escarole",
  "Beer - Heinekin",
  "Sugar - Brown",
  "Fork - Plastic",
  "Cheese - Augre Des Champs",
  "Bread - White Epi Baguette",
  "Chocolate - Pistoles, White",
  "Ham - Cooked Italian",
  "Wine - White, Lindemans Bin 95",
  "Ostrich - Prime Cut",
  "Fond - Neutral",
  "Coffee - Dark Roast",
  "Sobe - Cranberry Grapefruit",
  "Bread - Onion Focaccia",
  "Initation Crab Meat",
  "Veal - Brisket, Provimi,bnls",
  "Lemonade - Strawberry, 591 Ml",
  "Sauce - Hoisin",
  "Beef - Rouladin, Sliced",
  "Wine - Chateau Aqueria Tavel",
  "Steampan - Foil",
  "Cheese - Feta",
  "Chips - Doritos",
  "Table Cloth 54x54 White",
  "Oil - Safflower",
  "Apricots Fresh",
  "Bar - Sweet And Salty Chocolate",
  "Broom - Angled",
  "Plums - Red",
  "Cheese - Swiss Sliced",
  "Shrimp - Black Tiger 13/15",
  "Foam Espresso Cup Plain White",
  "Beef - Top Butt",
  "Pasta - Bauletti, Chicken White",
  "Butter Balls Salted",
  "Rum - Cream, Amarula",
  "Bread - Bistro White",
  "Tomatoes - Plum, Canned",
  "Wine - Alsace Riesling Reserve",
  "Cheese Cloth",
  "Nantucket - Orange Mango Cktl",
  "Bread - Roll, Calabrese",
  "Gatorade - Xfactor Berry",
  "Milk - Chocolate 500ml",
  "Wine - Ej Gallo Sonoma",
  "Cheese - Bakers Cream Cheese",
  "Devonshire Cream",
  "Lamb - Ground",
  "Soup - Campbells, Butternut",
  "Fudge - Cream Fudge",
  "Beer - Sleeman Fine Porter",
  "Limes",
  "Spice - Paprika",
  "Yogurt - Cherry, 175 Gr",
  "Cumin - Ground",
  "Pike - Frozen Fillet",
  "Lid - 3oz Med Rec",
  "Chicken - Wings, Tip Off",
  "Chevere Logs",
  "Chinese Foods - Pepper Beef",
  "Bread - Onion Focaccia",
  "Wine - Chateau Bonnet",
  "Beer - Tetleys",
  "Iced Tea - Lemon, 340ml",
  "Shrimp - 16/20, Iqf, Shell On",
  "Beef - Striploin Aa",
  "Melon - Watermelon, Seedless",
  "Nut - Almond, Blanched, Whole",
  "Mushroom - Oyster, Fresh",
  "Celery",
  "Spice - Onion Powder Granulated",
  "Lamb - Rack",
  "Shrimp - 31/40",
  "Towels - Paper / Kraft",
  "Cheese - Camembert",
  "Laundry - Bag Cloth",
  "Ezy Change Mophandle",
  "Dried Peach",
  "Syrup - Monin, Amaretta",
  "Mace",
  "Tomatoes - Orange",
  "Veal - Bones",
  "Sage - Ground",
  "Wine - Fontanafredda Barolo",
  "Bread - Pain Au Liat X12",
  "Soup - Knorr, French Onion",
  "Canada Dry",
  "Nut - Hazelnut, Whole",
  "Raisin - Dark",
  "Syrup - Golden, Lyles",
  "Pasta - Shells, Medium, Dry",
  "Wine - Chateauneuf Du Pape",
  "Cups 10oz Trans",
  "Beer - Mill St Organic",
  "Chervil - Fresh",
  "Glass - Juice Clear 5oz 55005",
  "Cake Circle, Paprus",
  "Food Colouring - Pink",
  "Energy Drink - Franks Original",
  "Vinegar - White Wine",
  "Sausage - Breakfast",
  "Milk 2% 500 Ml",
  "Peach - Halves",
  "Pepper - Chili Powder",
  "Mushroom - White Button",
  "Crackers - Trio",
  "Milk - Chocolate 500ml",
  "Lamb - Whole Head Off",
  "Beef - Baby, Liver",
  "Beef - Ox Tail, Frozen",
  "Everfresh Products",
  "Goat - Whole Cut",
  "Chocolate - Mi - Amere Semi",
  "Wine - Carmenere Casillero Del",
  "Extract - Almond",
  "Cookies Oatmeal Raisin",
  "Soup - French Can Pea",
  "Cheese - Grana Padano",
  "Noodles - Cellophane, Thin",
  "Glass - Juice Clear 5oz 55005",
  "Tomatillo",
  "Goulash Seasoning",
  "Pepper - Cubanelle",
  "Rabbit - Saddles",
  "Wine - White, Chardonnay",
  "Coconut - Shredded, Unsweet",
  "Haggis",
  "Wine - Red, Lurton Merlot De",
  "Tarragon - Primerba, Paste",
  "Bar Mix - Lime",
  "Lamb - Shoulder",
  "Apron",
  "Pork - Ground",
  "Foil - 4oz Custard Cup",
  "Bread - Mini Hamburger Bun",
  "Amarula Cream",
  "Peach - Halves",
  "Lid Tray - 16in Dome",
  "Jolt Cola - Electric Blue",
  "Veal - Bones",
  "Lamb - Shoulder, Boneless",
  "Wanton Wrap",
  "Pie Filling - Cherry",
  "Onions - Red Pearl",
  "Goat - Leg",
  "Sage - Fresh",
  "Oil - Macadamia",
  "Salt And Pepper Mix - Black",
  "Wine - Ruffino Chianti",
  "Breakfast Quesadillas",
  "Mahi Mahi",
  "Sauce - Black Current, Dry Mix",
  "Sugar - Invert",
  "Ranchero - Primerba, Paste",
  "Chicken - Livers",
  "Dc - Sakura Fu",
  "Cake Circle, Foil, Scallop",
  "Pectin",
  "Garlic - Peeled",
  "Cheese - Mix",
  "Sword Pick Asst",
  "Veal - Loin",
  "Scotch - Queen Anne",
  "Wanton Wrap",
  "Tomatoes",
  "Tomatoes Tear Drop",
  "Nut - Walnut, Pieces",
  "Heavy Duty Dust Pan",
  "Pastry - Cheese Baked Scones",
  "Table Cloth 91x91 Colour",
  "Haggis",
  "Mushroom - Shitake, Fresh",
  "Mushroom - Shitake, Dry",
  "Butcher Twine 4r",
  "Dip - Tapenade",
  "Water - Spring Water 500ml",
  "Chocolate - Compound Coating",
  "Juice - Apple, 341 Ml",
  "Wine - Touraine Azay - Le - Rideau",
  "Beer - Steamwhistle",
  "Oranges",
  "Wine La Vielle Ferme Cote Du",
  "Dr. Pepper - 355ml",
  "Napkin Colour",
  "Wine - Red, Black Opal Shiraz",
  "Lamb Leg - Bone - In Nz",
  "Sprouts - Pea",
  "Pastry - Carrot Muffin - Mini",
  "Syrup - Monin, Amaretta",
  "Cake - Bande Of Fruit",
  "Tart Shells - Sweet, 3",
  "Muffin - Zero Transfat",
  "Soup - Campbells Chili Veg",
  "Dasheen",
  "Beer - Mill St Organic",
  "Crab - Back Fin Meat, Canned",
  "Lettuce - Arugula",
  "Soup - French Onion, Dry",
  "Strawberries",
  "Mayonnaise",
  "Pear - Asian",
  "Beer - Upper Canada Lager",
  "Pasta - Canelloni, Single Serve",
  "Cheese Cloth",
  "Bacardi Raspberry",
  "Mikes Hard Lemonade",
  "Wine - Harrow Estates, Vidal",
  "Oil - Truffle, Black",
  "Beef - Chuck, Boneless",
  "Fish - Scallops, Cold Smoked",
  "Creme De Menthe Green",
  "Glucose",
  "Cookies Almond Hazelnut",
  "Bread - Roll, Italian",
  "Wine - White, Ej Gallo",
  "Cookie - Oreo 100x2",
  "Beef - Texas Style Burger",
  "Wine - Bourgogne 2002, La",
  "Chocolate Eclairs",
  "Extract - Rum",
  "Table Cloth 53x53 White",
  "Bread - Calabrese Baguette",
  "Bread Foccacia Whole",
  "Bar Nature Valley",
  "Jam - Raspberry,jar",
  "Cheese - Goat",
  "Pasta - Linguini, Dry",
  "Chicken - Base",
  "Latex Rubber Gloves Size 9",
  "The Pop Shoppe - Lime Rickey",
  "Apples - Sliced / Wedge",
  "Pail - 15l White, With Handle",
  "Bagelers - Cinn / Brown",
  "Dry Ice",
  "Coffee - Ristretto Coffee Capsule",
  "Potatoes - Instant, Mashed",
  "V8 - Tropical Blend",
  "Schnappes Peppermint - Walker",
  "Wine - Magnotta - Cab Franc",
  "Ham - Procutinni",
  "Honey - Comb",
  "Tomatoes - Diced, Canned",
  "Vodka - Moskovskaya",
  "Flour - Rye",
  "Lettuce - Curly Endive",
  "Lychee - Canned",
  "Pepper - Green Thai",
  "Cheese - Havarti, Roasted Garlic",
  "Banana",
  "Ice Cream Bar - Oreo Cone",
  "Pork - Loin, Center Cut",
  "Beef - Salted",
  "Wine - Casillero Deldiablo",
  "Muffins - Assorted",
  "Silicone Parch. 16.3x24.3",
  "Coffee - 10oz Cup 92961",
  "Bread - French Baquette",
  "Tobasco Sauce",
  "Soup - French Onion",
  "Clementine",
  "Nantucket Pine Orangebanana",
  "Wine - Sicilia Igt Nero Avola",
  "Wine - Ej Gallo Sonoma",
  "Oil - Olive, Extra Virgin",
  "Strawberries",
  "Nutmeg - Ground",
  "Green Scrubbie Pad H.duty",
  "Pork - Bones",
  "Pumpkin - Seed",
  "Wine - Saint - Bris 2002, Sauv",
  "Chocolate - Semi Sweet, Calets",
  "Mushroom - White Button",
  "Sprouts Dikon",
  "Wine - Malbec Trapiche Reserve",
  "Appetizer - Mango Chevre",
  "Magnotta - Bel Paese White",
  "Filo Dough",
  "Lamb - Shoulder, Boneless",
  "Port - 74 Brights",
  "Ice Cream Bar - Rolo Cone",
  "Oyster - In Shell",
  "Sauce - Plum",
  "Snapple - Mango Maddness",
  "Nantucket Apple Juice",
  "Veal - Inside",
  "Foam Cup 6 Oz",
  "Pastry - Cheese Baked Scones",
  "Flower - Commercial Bronze",
  "Cheese - Swiss",
  "Tofu - Soft",
  "Lamb - Ground",
  "Sobe - Berry Energy",
  "Tea - Herbal - 6 Asst",
  "Seaweed Green Sheets",
  "Mace",
  "Ice Cream - Strawberry",
  "Oil - Peanut",
  "Orange - Blood",
  "Soup - Campbells Chili",
  "Anchovy In Oil",
  "Mustard - Pommery",
  "Beer - Sleemans Honey Brown",
  "Nutmeg - Ground",
  "Wine - Chateau Bonnet",
  "Wine - Red, Antinori Santa",
  "Pop - Club Soda Can",
  "Coffee - Egg Nog Capuccino",
  "Orange Roughy 6/8 Oz",
  "Godiva White Chocolate",
  "Wine - Beaujolais Villages",
  "Beef Tenderloin Aaa",
  "Pear - Prickly",
  "Sugar - Monocystal / Rock",
  "Tea - Camomele",
  "Oil - Shortening - All - Purpose",
  "Beans - Wax",
  "Chicken - Diced, Cooked",
  "Creme De Banane - Marie",
  "Muffin - Carrot Individual Wrap",
  "Beef - Prime Rib Aaa",
  "Brandy Apricot",
  "Glucose",
  "Oranges",
  "Sauce Tomato Pouch",
  "Longos - Lasagna Veg",
  "Dooleys Toffee",
  "Vermouth - Sweet, Cinzano",
  "Wine - Saint - Bris 2002, Sauv",
  "Lamb Shoulder Boneless Nz",
  "Ice Cream - Strawberry",
  "Foil Wrap",
  "Limes",
  "Bread - Frozen Basket Variety",
  "Muffin Batt - Blueberry Passion",
  "Rice - Sushi",
  "Pan Grease",
  "Quail - Eggs, Fresh",
  "Parsley - Dried",
  "Ginsing - Fresh",
  "Island Oasis - Peach Daiquiri",
  "Venison - Liver",
  "Sea Bass - Fillets",
  "Wine - Valpolicella Masi",
  "Water - Aquafina Vitamin",
  "Nantucket - Kiwi Berry Cktl.",
  "Quinoa",
  "Sponge Cake Mix - Chocolate",
  "Lemon Balm - Fresh",
  "Hot Choc Vending",
  "Tuna - Canned, Flaked, Light",
  "Wine - Shiraz Wolf Blass Premium",
  "Lotus Rootlets - Canned",
  "Pepper - Green, Chili",
  "Salmon - Canned",
  "Vaccum Bag - 14x20",
  "Wine - White, Pinot Grigio",
  "Caviar - Salmon",
  "Nantucket - Orange Mango Cktl",
  "Veal - Sweetbread",
  "Wine La Vielle Ferme Cote Du",
  "Shiro Miso",
  "Eggs - Extra Large",
  "Bar Nature Valley",
  "Yogurt - French Vanilla",
  "Lettuce - Lolla Rosa",
  "Cheese Cloth No 60",
  "Pork - Side Ribs",
  "Garam Masala Powder",
  "Onions - Pearl",
  "Chocolate - Sugar Free Semi Choc",
  "Cheese - Gorgonzola",
  "Mushroom - Enoki, Dry",
  "Bar Mix - Lime",
  "Salami - Genova",
  "Rice Paper",
  "Dish Towel",
  "Mushroom - Chantrelle, Fresh",
  "Veal - Shank, Pieces",
  "Veal - Liver",
  "Pork - Loin, Bone - In",
  "Wine - Cahors Ac 2000, Clos",
  "Tea - Grapefruit Green Tea",
  "Truffle Shells - White Chocolate",
  "Cup - 8oz Coffee Perforated",
  "Rum - White, Gg White",
  "Wine - Cave Springs Dry Riesling",
  "Tart - Butter Plain Squares",
  "Salmon - Atlantic, No Skin",
  "Coffee Swiss Choc Almond",
  "Soho Lychee Liqueur",
  "Wine - Chianti Classico Riserva",
  "Cheese - Cheddar With Claret",
  "Beer - Muskoka Cream Ale",
  "Milk - Buttermilk",
  "Scallops - U - 10",
  "Mangostein",
  "Quail - Whole, Bone - In",
  "Beef - Bones, Cut - Up",
  "Glaze - Clear",
  "Lamb Shoulder Boneless Nz",
  "Beans - Fava Fresh",
  "Tomato - Green",
  "Momiji Oroshi Chili Sauce",
  "Plastic Wrap",
  "Nori Sea Weed",
  "Pastry - Baked Scones - Mini",
  "Juice - Cranberry 284ml",
  "Appetizer - Veg Assortment",
  "Wine - Red, Mouton Cadet",
  "Sponge Cake Mix - Chocolate",
  "Onions - Cippolini",
  "Daikon Radish",
  "Wine - Barossa Valley Estate",
  "Bread - White Epi Baguette",
  "Table Cloth 62x114 Colour",
  "Beans - Fine",
  "Canada Dry",
  "Towel Multifold",
  "Pastry - Baked Cinnamon Stick",
  "Oil - Sunflower",
  "Lettuce - Iceberg",
  "Yogurt - Blueberry, 175 Gr",
  "Nantucket - Carrot Orange",
  "Bread - Roll, Calabrese",
  "Sprite - 355 Ml",
  "Cake - Night And Day Choclate",
  "Bay Leaf Fresh",
  "Soup Campbells Turkey Veg.",
  "Wine - Merlot Vina Carmen",
  "Pork - Belly Fresh",
  "Wine - Red, Cabernet Merlot",
  "Sprouts - Alfalfa",
  "Sugar - White Packet",
  "Cabbage - Nappa",
  "Chips Potato Salt Vinegar 43g",
  "Pineapple - Regular",
  "Sauce - Mint",
  "Beer - Camerons Auburn",
  "Currants",
  "Pasta - Lasagna, Dry",
  "Radish - Black, Winter, Organic",
  "Cookie Dough - Chunky",
  "Milk - Skim",
  "Cheese - Brie, Cups 125g",
  "Pork - Tenderloin, Fresh",
  "Soup - Base Broth Chix",
  "Chicken - Whole Roasting",
  "Bandage - Finger Cots",
  "Containter - 3oz Microwave Rect.",
  "Tomatoes - Diced, Canned",
  "Tuna - Bluefin",
  "Flour - Bran, Red",
  "Mackerel Whole Fresh",
  "Chocolate Bar - Smarties",
  "Slt - Individual Portions",
  "Muffin Mix - Banana Nut",
  "Foil - Round Foil",
  "Brandy Cherry - Mcguinness",
  "Cornish Hen",
  "Pasta - Penne, Lisce, Dry",
  "Potatoes - Parissienne",
  "Coffee - Decaffeinato Coffee",
  "Eggplant Oriental",
  "Pork - Inside",
  "Sparkling Wine - Rose, Freixenet",
  "Wine - Cava Aria Estate Brut",
  "Sobe - Tropical Energy",
  "Filter - Coffee",
  "Bread - Sour Sticks With Onion",
  "Crackers - Melba Toast",
  "Lamb - Loin Chops",
  "Wooden Mop Handle",
  "Wine - Red, Colio Cabernet",
  "Towels - Paper / Kraft",
  "Scallop - St. Jaques",
  "Chicken - Soup Base",
  "Quiche Assorted",
  "Chocolate - Feathers",
  "Tomatoes",
  "External Supplier",
  "Red Cod Fillets - 225g",
  "Oven Mitts - 15 Inch",
  "Chicken - Livers",
  "Puff Pastry - Slab",
  "Sugar - Fine",
  "Coriander - Ground",
  "Juice - Ocean Spray Kiwi",
  "Cheese - Fontina",
  "Olives - Stuffed",
  "Wine - Red, Black Opal Shiraz",
  "Scallops - 20/30",
  "Crackers Cheez It",
  "Juice - Apple, 1.36l",
  "Clementine",
  "Bagel - Everything Presliced",
  "Icecream - Dstk Super Cone",
  "Cheese - Cambozola",
  "Bread - Calabrese Baguette",
  "Longos - Lasagna Beef",
  "Goat - Leg",
  "Pernod",
  "Lid - High Heat, Super Clear",
  "Instant Coffee",
  "Seedlings - Buckwheat, Organic",
  "Coffee - Irish Cream",
  "Lamb - Loin, Trimmed, Boneless",
  "Aspic - Clear",
  "Pork - Backs - Boneless",
  "French Pastries",
  "Chocolate - Semi Sweet, Calets",
  "Jolt Cola - Red Eye",
  "Sauce Bbq Smokey",
  "Vinegar - White",
  "Muffin Mix - Chocolate Chip",
  "Table Cloth 90x90 White",
  "Rice - Long Grain",
  "Kiwi Gold Zespri",
  "Shiro Miso",
  "Ice Cream Bar - Oreo Cone",
  "Appetizer - Chicken Satay",
  "Table Cloth 53x53 White",
  "Lamb - Shoulder, Boneless",
  "Tofu - Soft",
  "Wine - Chablis J Moreau Et Fils",
  "Wine - Ruffino Chianti Classico",
  "Asparagus - Green, Fresh",
  "Pizza Pizza Dough",
  "Chinese Foods - Cantonese",
  "Salmon Atl.whole 8 - 10 Lb",
  "Cheese - Mozzarella, Shredded",
  "Ostrich - Fan Fillet",
  "Oil - Olive Bertolli",
  "Dr. Pepper - 355ml",
  "Wooden Mop Handle",
  "Flour - Corn, Fine",
  "Juice - Apple Cider",
  "Wine - Sake",
  "Ham Black Forest",
  "Soup - Boston Clam Chowder",
  "Clam - Cherrystone",
  "Bread - Roll, Soft White Round",
  "Long Island Ice Tea",
  "Wine - Cotes Du Rhone",
  "Tomato Puree",
  "Plaintain",
  "Bar Mix - Lemon",
  "Cauliflower",
  "Soup - Knorr, Chicken Noodle",
  "Sauce - Apple, Unsweetened",
  "Brandy - Bar",
  "Beer - True North Strong Ale",
  "Tea - Apple Green Tea",
  "Honey - Lavender",
  "Sauce - Fish 25 Ozf Bottle",
  "Lamb - Leg, Diced",
  "Cheese - Cheddar, Medium",
  "Wine - Ej Gallo Sonoma",
  "Pasta - Penne Primavera, Single",
  "Sardines",
  "Corn Kernels - Frozen",
  "Potatoes - Fingerling 4 Oz",
  "Pastry - Apple Large",
  "Bread - Hot Dog Buns",
  "Compound - Orange",
  "Chicken - Leg, Fresh",
  "Bread - White Epi Baguette",
  "Bag Stand",
  "Drambuie",
  "Green Scrubbie Pad H.duty",
  "Coffee - Decaffeinato Coffee",
  "Cabbage - Green",
  "Zucchini - Yellow",
  "Bread Base - Goodhearth",
  "Plate Pie Foil",
  "Cheese - Brie, Cups 125g",
  "Calypso - Pineapple Passion",
  "Cake - Mini Potato Pancake",
  "Vegetable - Base",
  "Spinach - Spinach Leaf",
  "Grapefruit - White",
  "Pepper - Chillies, Crushed",
  "Cranberries - Fresh",
  "Bay Leaf Fresh",
  "Cheese - Mascarpone",
  "Cookies - Englishbay Oatmeal",
  "Sugar - Fine",
  "Ocean Spray - Kiwi Strawberry",
  "Syrup - Pancake",
  "Yogurt - French Vanilla",
  "Pail - 15l White, With Handle",
  "Lamb - Whole Head Off,nz",
  "Pork - Bacon, Sliced",
  "Chicken Breast Wing On",
  "Cup - 6oz, Foam",
  "Mussels - Cultivated",
  "Olives - Kalamata",
  "Beer - Sleemans Honey Brown",
  "Pepper - Pablano",
  "Carrots - Mini, Stem On",
  "Wine - Red, Cooking",
  "Island Oasis - Wildberry",
  "Ecolab - Hobart Washarm End Cap",
  "Energy Drink - Redbull 355ml",
  "White Fish - Filets",
  "Chocolate - Dark",
  "Cranberries - Fresh",
  "Flour - Masa De Harina Mexican",
  "Russian Prince",
  "Appetizer - Mushroom Tart",
  "Rabbit - Legs",
  "Bread Foccacia Whole",
  "Rabbit - Whole",
  "Skirt - 29 Foot",
  "Appetizer - Shrimp Puff",
  "Vegetable - Base",
  "Bagelers - Cinn / Brown Sugar",
  "Blueberries",
  "Spinach - Baby",
  "Wine - White, Ej Gallo",
  "Lettuce - Radicchio",
  "Wine - Guy Sage Touraine",
  "Peach - Fresh",
  "Wine - Dubouef Macon - Villages",
  "Juice - Lime",
  "Basil - Dry, Rubbed",
  "Eggplant Oriental",
  "Pasta - Canelloni",
  "Bar - Granola Trail Mix Fruit Nut",
  "Sea Urchin",
  "Oregano - Fresh",
  "Paper Towel Touchless",
  "Cookies - Amaretto",
  "Wine - Magnotta - Pinot Gris Sr",
  "Cod - Fillets",
  "Plate Foam Laminated 9in Blk",
  "Bag - Bread, White, Plain",
  "Kiwi Gold Zespri",
  "Flour - Strong Pizza",
  "Sprouts - Bean",
  "Bread - Olive Dinner Roll",
  "Flavouring - Orange",
  "Ocean Spray - Kiwi Strawberry",
  "Tomatillo",
  "Salt - Rock, Course",
  "The Pop Shoppe - Black Cherry",
  "Cherries - Fresh",
  "Pork Casing",
  "Garlic",
  "Pasta - Cappellini, Dry",
  "Gingerale - Diet - Schweppes",
  "Kellogs Cereal In A Cup",
  "Lettuce - Romaine, Heart",
  "Straws - Cocktale",
  "Potatoes - Pei 10 Oz",
  "Cake - Lemon Chiffon",
  "Wine - Fino Tio Pepe Gonzalez",
  "Cherries - Bing, Canned",
  "Lettuce - Arugula",
  "Mousse - Banana Chocolate",
  "Island Oasis - Peach Daiquiri",
  "Fruit Salad Deluxe",
  "Chocolate Liqueur - Godet White",
  "Beer - Labatt Blue",
  "Pineapple - Golden",
  "Appetizer - Tarragon Chicken",
  "Coffee - Flavoured",
  "Wine - Red, Mosaic Zweigelt",
  "Tamarillo",
  "Cheese - Grana Padano",
  "Carrots - Jumbo",
  "Cookie - Oreo 100x2",
  "Crab Meat Claw Pasteurise",
  "Basil - Pesto Sauce",
  "Soda Water - Club Soda, 355 Ml",
  "Corn Meal",
  "Chicken - Thigh, Bone In",
  "Pear - Halves",
  "Scrubbie - Scotchbrite Hand Pad",
  "Icecream - Dstk Strw Chseck",
  "Rice - 7 Grain Blend",
  "Beans - Wax",
  "Pork - Shoulder",
  "Mushroom - Chanterelle, Dry",
  "Pants Custom Dry Clean",
  "Vinegar - White Wine",
  "Pork - Caul Fat",
  "Soup Campbells Mexicali Tortilla",
  "Hagen Daza - Dk Choocolate",
  "Beer - Maudite",
  "Dry Ice",
  "Pineapple - Canned, Rings",
  "Juice - Grapefruit, 341 Ml",
  "Flower - Carnations",
  "Turkey - Breast, Boneless Sk On",
  "Juice Peach Nectar",
  "Fond - Chocolate",
  "Garbage Bags - Clear",
  "Asparagus - Green, Fresh",
  "Cheese - Swiss Sliced",
  "Rosemary - Primerba, Paste",
  "Beer - Camerons Auburn",
  "Gatorade - Fruit Punch",
  "Squid - U - 10 Thailand",
  "Baking Soda",
  "Island Oasis - Magarita Mix",
  "Wine - White, Cooking",
  "Vodka - Hot, Lnferno",
  "Soap - Mr.clean Floor Soap",
  "Wood Chips - Regular",
  "Table Cloth 62x114 Colour",
  "Chocolate - Sugar Free Semi Choc",
  "Pop Shoppe Cream Soda",
  "Sausage - Breakfast",
  "Muffin - Banana Nut Individual",
  "Soap - Mr.clean Floor Soap",
  "Bag - Regular Kraft 20 Lb",
  "Beans - Long, Chinese",
  "Chutney Sauce - Mango",
  "Tomatillo",
  "Container Clear 8 Oz",
  "Wine La Vielle Ferme Cote Du",
  "Wine - White, Lindemans Bin 95",
  "Calypso - Strawberry Lemonade",
  "Cakes Assorted",
  "Cheese - Mozzarella",
  "Carbonated Water - Peach",
  "Raspberries - Frozen",
  "Appetizer - Assorted Box",
  "True - Vue Containers",
  "Chef Hat 25cm",
  "Pastry - Chocolate Chip Muffin",
  "Turkey - Breast, Smoked",
  "Wine - Cabernet Sauvignon",
  "Juice - Lagoon Mango",
  "Sauce - Soya, Light",
  "Apple - Macintosh",
  "Icecream Bar - Del Monte",
  "Flour - Teff",
  "Five Alive Citrus",
  "Ecolab - Hobart Washarm End Cap",
  "Momiji Oroshi Chili Sauce",
  "Kohlrabi",
  "Beef - Cooked, Corned",
  "Table Cloth 81x81 White",
  "Coffee Caramel Biscotti",
  "Skirt - 24 Foot",
  "Beer - True North Strong Ale",
  "Cheese - Goat",
  "Sauce - Sesame Thai Dressing",
  "Arizona - Green Tea",
  "Coconut - Shredded, Unsweet",
  "Lobster - Canned Premium",
  "Bread - Granary Small Pull",
  "Potatoes - Yukon Gold, 80 Ct",
  "Sauce - Thousand Island",
  "Wine - Taylors Reserve",
  "Chevril",
  "Bread - Pita, Mini",
  "Cheese - Boursin, Garlic / Herbs",
  "Bread - Rye",
  "Langers - Ruby Red Grapfruit",
  "Wine - Chateau Timberlay",
  "Foil Wrap",
  "Rum - Light, Captain Morgan",
  "Crab - Back Fin Meat, Canned",
  "Campari",
  "Syrup - Golden, Lyles",
  "Tamarillo",
  "Persimmons",
  "Bacardi Limon",
  "Flour - Whole Wheat",
  "Yogurt - Banana, 175 Gr",
  "Wine - Jaboulet Cotes Du Rhone",
  "Cheese - Comte",
  "French Kiss Vanilla",
  "Shrimp - 21/25, Peel And Deviened",
  "Oil - Shortening - All - Purpose",
  "Calypso - Pineapple Passion",
  "Black Currants",
  "Chicken - Livers",
  "Red Currants",
  "Muffin Hinge - 211n",
  "Tart - Lemon",
  "Tortillas - Flour, 10",
  "External Supplier",
  "Juice - Ocean Spray Kiwi",
  "Chilli Paste, Hot Sambal Oelek",
  "Sugar - Cubes",
  "Lettuce - Curly Endive",
  "Trueblue - Blueberry Cranberry",
  "Flour Pastry Super Fine",
  "Wine - Magnotta - Belpaese",
  "French Kiss Vanilla",
  "Wine - Magnotta - Pinot Gris Sr",
  "Gatorade - Xfactor Berry",
  "Grouper - Fresh",
  "Longan",
  "Pesto - Primerba, Paste",
  "Crackers - Soda / Saltins",
  "Cookie Double Choco",
  "Juice - Apple Cider",
  "Cake - Dulce De Leche",
  "Laundry - Bag Cloth",
  "Red Pepper Paste",
  "Kaffir Lime Leaves",
  "Goat - Leg"
];

const meta: Meta = {
  title: 'Hooks/useFuzzySearch',
  parameters: {
    docs: {
      description: {
        component: 'A simple hook prooviding fuzzy searching - approximate rather than exact pattern matching.'
      },
    }
  }
};
export default meta;

type Story = StoryObj;

const FuzzySearchStory = ({ matchStrategy }: { matchStrategy: 'off' | 'smart' | 'aggressive' }) => {
  const { query, setQuery, results } = useFuzzySearch({
    searchArray: items,
    matchStrategy,
    getSearchString: (item) => item,
  });

  return (
    <Box>
      <Input
        value={query}
        onChange={setQuery}
        placeholder='Begin writing...'
      />
      <Box mt={2}>
        {results.length === 0 && query !== '' && (
          <div>No entries</div>
        )}
        {results.map((item, index) => (
          <Box key={index}>{item}</Box>
        ))}
      </Box>
    </Box>
  );
};

export const SimpleSearch: Story = {
  render: () => <FuzzySearchStory matchStrategy="off" />,
};

export const FuzzySearch: Story = {
  render: () => <FuzzySearchStory matchStrategy="smart" />,
};

export const AgressiveSearch: Story = {
  render: () => <FuzzySearchStory matchStrategy="aggressive" />,
};
